workflows:
  ios-simulator:
    name: iOS Simulator
    environment:
      flutter: 3.27.3
      xcode: 16.2
    scripts:
      - flutter pub get
      - flutter build ios --simulator
      - find build/ios/iphonesimulator -name "*.app"
    artifacts:
      - build/ios/iphonesimulator/*.app

  ios-testflight:
    name: iOS TestFlight
    environment:
      flutter: 3.27.3
      xcode: 16.2
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lingumoro.teacher
    scripts:
      - flutter pub get
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        submit_to_testflight: true
