workflows:
  ios:
    name: iOS Teacher (TestFlight)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        provisioning_profiles:
          - CodemagicTeacher
        certificates:
          - CodemagicCert

    scripts:
      - name: Get packages
        script: |
          flutter clean
          flutter pub get

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Build IPA (Teacher)
        script: |
          flutter build ipa --release --export-options-plist=ios/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
